<?php
$titulo = "Alto entendimiento para el alto rendimiento";
$autor="Rubén Jerónimo";
$categoria="Equipos";
$fecha="15 de junio 2023";
$subtitulo = "Algunas empresas están mejorando el desempeño de sus líderes (y sus resultados) mediante el uso de herramientas para que entiendan mejor cómo piensan. ¿Qué beneficios puede traer esto a su organización?";
$imagen1 = "https://equiposqueaprenden.es/knowriish/blog/imagenes//10_entendimiento1.jpg";
$contenido1 = <<<HTML
    <p id="descripcionPost">¿A alguien le suena esa sensación de jefes y compis con la lengua fuera y el viernes hablar de ello como el que ha cazado un oso con un cuchillo de untar mantequilla? Confundir el agotamiento energético con el esfuerzo, la actividad con la productividad, el objetivo con la misión nos llevan invariablemente a equipos fatigados y cada vez menos motivados.<br><b>Y así es muy difícil llegar al alto rendimiento. </b></p>
    <p>Supongo que no seré la única persona  a la que se le encoge el estómago cuando ve escritos juntos los términos “alto” y “rendimiento”... Aparecen combinados de manera habitual pero ¿seguro que conocemos los conceptos en profundidad?.<br>Las personas a cargo de liderar equipos corremos el riesgo de confundir alto rendimiento con “exprimir al máximo” a las personas debido a la indefinición, el desconocimiento o lo que hemos asumido en nuestra cabeza que significa esto del alto rendimiento, por eso es importante pararnos a pensar y clarificar qué es esto del alto desempeño.</p>
    <h4>Pararse a pensar y definir una estrategia bottom up (para recoger resultados, primero hay que sembrar)</h4>
    <p>Llevo tiempo pensando que quizá las prisas nos están dando la excusa para no empezar a cultivar una verdadera cultura de entendimiento.<br>Tu y yo hemos dicho en muchas más ocasiones de las que se lo merecían: “ahora no, que no tengo tiempo”. Y sobre todo en cuestiones más estratégicas, mimando la operativa y las tareas concretas por encima de la dirección a seguir.</p>
HTML;
$imagen2 = "https://equiposqueaprenden.es/knowriish/blog/imagenes/10_entendimiento2.jpg";
$contenido2 = <<<HTML
    <p>Como dice <a href="https://twitter.com/EduardoBurgoa" target="_blank">E. Burgoa:</a>  “La verdadera procrastinación es no salir de la dinámica del día a día y parar a pensar”. Y es precisamente de ese parar y pensar de dónde surge el alto desempeño, de conceder importancia (y tiempo real) a los propósitos más profundos del equipo. <br>Una buena aproximación a las organizaciones que parten del entendimiento y lo aprovechan para navegar en la complejidad la presenta Niels Pflaeging en su libro: <a href="https://www.amazon.com/Organize-Complexity-High-Performance-Organization-Publishing/dp/0991537602" target="_blank">Organize for complexity</a> al tratar las interacciones entre los individuos como el verdadero potencial donde se evidenciará el impacto. Al trabajar sobre núcleos humanos reducidos con compromisos y objetivos comunes, sustituyendo al departamento por células, agilizamos la toma de decisión. Esta contribuye a la autoestima del equipo que redunda en motivación intrínseca de los individuos que invariablemente, se sienten reconfortados con la propia idea del equipo y la pertenencia al mismo. </p>
    <p>Cualquier organización puede hacer del entorno compartido de sus integrantes una experiencia gratificante o un espacio hostil. <br>Está claro que lo primero no es gratis. Requiere tiempo, esfuerzo y en numerosas ocasiones, grandes cantidades de dinero, pero lo que devuelve es mucho mayor (hecho con cautela, sensibilidad y poniendo en el centro a las personas) en términos de rentabilidad, ya que la recompensa es un entorno que favorece la proactividad y el autoliderazgo. <br>El alto rendimiento se establece en términos casi biológicos, donde unas moléculas colaboran con otras y saben que el éxito solo puede producirse cuando es para todas ellas y no para una sola.Saben aprovechar el constante cambio de su entorno para evolucionar e incluso lo estimulan para que suceda, fomentando la innovación.<br>Si queremos (no digamos ya si exigimos) el alto rendimiento, tenemos que tener disposición a cambiar nuestra forma de interactuar y adquirir habilidades de alto entendimiento, que nos den claridad tanto en el objetivo y las estrategias a seguir, como en las diferentes realidades que va a vivir ese equipo y sus miembros en el viaje.<br><b>Y si deseamos entender bien, creo que es muy necesario que aprendamos a preguntar. Sin juzgar ni evaluar, solo preguntar. Pero sobre todo compartir. </b></p>
        <p>Una organización que pretende tener equipos de alto rendimiento debe pasar invariablemente por la circunstancia de exponerse e incluso de ser rechazada. Debe ser honesta con sus miembros y mostrarse tal y como es. <br>¡Ojo!, esto no pretende ser un alegato hippy. Esto va de resultados. De lo que supone conseguirlos pero sobre todo, identificar los que son adecuados para nuestra estratégia. Y de ahí que me pregunte si podemos hacer que un equipo sea de alto rendimiento sin que el entorno sea de alto entendimiento, alta comprensión, estimulación y empatía y cómo fomentar que esta sea la atmósfera respirable. <br>Al fin y al cabo, ¿no queremos cada cual dar lo mejor? y en equipo ¿no queremos que nuestro equipo haga cosas cada vez más aspiracionales y llegue más lejos?<br><a href="https://www.amazon.com/-/es/Pekka-Himanen/dp/0375505660/ref=sr_1_1?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3LHQCZBGFRUQU&keywords=hacker+ethic&qid=1686818563&s=books&sprefix=hacker+ethic%2Cstripbooks-intl-ship%2C242&sr=1-1" target="_blank">La ética del hacker</a> de Pekka Himanen aporta otra forma de enmarcar las relaciones laborales más allá de la devoción/sumisión y cómo un grupo de personas bien motivadas, con recursos y conocimiento son capaces de alcanzar cotas mucho más altas que equipos top. <br>Y lo mejor de todo es que esto de hacer que el entorno sea de alto entendimiento no es algo para delegar sino para interiorizar. Poder extraer lo mejor de mí significa poder evaluar el mayor impacto positivo posible y distinguir entre lo que me va a permitir alcanzarlo y lo que me va a paralizar.<br>Y si el compromiso es compartido, me pregunto si no manejamos una serie de intangibles o aspectos abstractos erróneos que nos llevan a conceptos más erróneos todavía, como el alto rendimiento.</p>
        <h4>Un nuevo liderazgo para el alto entendimiento</h4>
        <p>Necesitamos cambiar el paradigma del liderazgo, al menos en parte, para lograr ese nuevo entendimiento. <br><b>Un liderazgo que fomente la cultura de entendimiento debe pasar invariablemente por la capacidad de generar confianza en el equipo en múltiples direcciones. </b></p>
HTML;
$contenido3 = <<<HTML
    <p>Podemos asimilar al equipo a un ser inteligente y como tal se comporta. Y esa inteligencia colectiva magnificamente descrita por <a href="https://twitter.com/arey" target="_blank">Amalio Rey</a> en su <a href="https://www.amazon.com/-/es/Amalio-Rey-ebook/dp/B09V1NRW6Z/ref=sr_1_1?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2X5UWUPC8CMNO&keywords=inteligencia+colectiva&qid=1686818758&s=books&sprefix=inteligencia+colectiv%2Cstripbooks-intl-ship%2C183&sr=1-1" target="_blank">Libro de la inteligencia colectiva</a> la podemos potenciar desde un tipo de liderazgo que mejore la autoestima del equipo y sus habilidades. Finalmente esto mejora cuando permitimos al equipo y sus miembros tomar decisiones, permutando los roles donde los líderes centralizaban su toma de decisiones frente al servicio e información proporcionada por los miembros, por otra donde el liderazgo esté al servicio de los elementos de esa célula y sobre todo, sus interacciones. <br>Un entorno de alto entendimiento comprenderá que su interacción generará invariablemente cambios en las realidades de sus miembros y atenderá a sus necesidades para alcanzar el objetivo.<br>Lógicamente, para ello se necesitan líderes que realmente actúen como búhos, observando cualquier movimiento a su alrededor y evitar el viejo “anteojerismo” que al burro le ayuda a continuar de frente, pero sólo a él, y sin opción a evaluar el entorno y decidir la dirección.<br>Si de verdad quieres que tu equipo sea de alto rendimiento solo escúchalo, evitando el prejuicio y favoreciendo el postjuicio que surge de las ideas conectadas con los miembros y dan sentido a las acciones posteriores. <br>Indícale el camino para obtener esos tan ansiados resultados, pero déjale probar su propio camino. Lidera sin dolor y con entendimiento y verás cómo tu equipo es el que termina llevándote a ti al alto rendimiento.</p>
    <p>¡Espero que lo disfruten!</p>
HTML;
include 'plantillaPost.php';
?>