<?php
$titulo = "El café es conocimiento";
$autor="Rubén Jerónimo";
$categoria="Conocimiento";
$fecha="15 de junio 2023";
$subtitulo = "La experiencia como motor del aprendizaje en equipo.";
$imagen1 = "https://equiposqueaprenden.es/knowriish/blog/imagenes//cafeconocimiento1.jpg";
$contenido1 = <<<HTML
    <h4>El conocimiento que se escapó del libro</h4>
    <p id="descripcionPost">El poder de lo escrito es innegable. Se podría decir incluso que nada que no esté escrito, haya podido existir jamás. La propia historia nos revela que de no existir ciertos cronistas nunca habríamos sabido de la existencia de pueblos y culturas enteras debido a su carencia de escritura. Dejando a un lado lo ajustado a la realidad de la crónica realizada, lo cierto es que ese pueblo, desde el punto de vista actual, jamás habría existido. </p>
    <p>De ese modo, el conocimiento humano requiere de la cristalización constante y, más allá de la necesidad de la propia supervivencia del conocimiento, esto hace que se propague, que se aplique y compruebe en distintos entornos y finalmente sea aceptada o no por un grupo complejo de individuos como sabiduría. Pero, ¿qué conocimiento es el que merece ser cristalizado?<br>Existe un modelo de generación del conocimiento del que ya hemos hablado varias veces pero del que me gustaría profundizar en uno de sus conceptos. Ese modelo es el ideado por Nonaka y Takeuchi en su libro <a href="https://www.amazon.es/Knowledge-Creating-Company-Japanese-Companies-Innovation/dp/0195092694" target="_blank">The knowledge creating company</a> que, aun con sus más de 20 años desde su publicación, sigue teniendo una vigencia con gran impacto a día de hoy.  En ese modelo, existe un tipo de conocimiento con mayúsculas: el conocimiento tácito. </p>
    <p>Ese tipo de conocimiento es el que deja un aroma a tu familia cuando recuerdas aquello que tu abuelo o abuela te contó aquella vez. Es una información de carácter absoluto en el imaginario y rara vez está equivocada.<br>Es también el recuerdo de la toma de decisión en aquel momento importante. Un momento que no tuvo réplica en tu historia personal y del que poco o nada sabías. Solo tu y tu experiencia contra el reto. Acertaste o fallaste, poco importa. Lo importante es el aprendizaje que se deslizó por las minúsculas fisuras de la experiencia y que hoy, es una verdad incuestionable.<br>De cualquier cosa que estuviesemos hablando en estos casos descritos, hay algo o mucho escrito, en libros o artículos, narrado en videos, podcast o hasta labrado en piedra o lo que sea, pero es muy difícil que exprese lo que ese conocimiento tácito ha hecho fluir. Ha comenzado la socialización del conocimiento. Aquí, la socialización es el huevo del que nacerá la gallina del conocimiento.</p>
    <h4>Compartir es amar. Socializar es aprender.</h4>
    <p>Por lo tanto, si damos por válida la premisa de que el aprendizaje surge de la socialización esto es, de la acción de transmitir información relevante en un contexto y tiempo determinado con la intención de fomentar en los agentes implicados una capacidad posterior de aplicación ampliada a la posible, antes de la propia socialización, podemos asumir que en gran medida la posibilidad de aprender y adquirir conocimiento pasa por la reunión con otros individuos, en contexto y tiempo similares. <br>Tenemos que entender que el conocimiento experiencial e intuitivo, es por definición el más complejo de transmitir. No está sujeto a reglas formales de aprendizaje, ni tiene indicadores que permitan evaluar el éxito. No hay forma de controlarlo ni filtrarlo. Simplemente es complejo y como tal lo debemos aceptar. Y no podemos negar su impacto como ya hemos ejemplificado con la conversación con los abuelos.<br>Todo comienza, por lo tanto, por sentarnos con alguien y comenzar una conversación. Tan fácil como eso. Una información que es difícil de ser expresada, finalmente logra ajustar sus procesos internos de articulación del lenguaje y surge como una revelación ante la sorpresa del receptor. </p>
HTML;
$imagen2 = "https://equiposqueaprenden.es/knowriish/blog/imagenes/cafeconocimiento3.jpg";
$contenido2 = <<<HTML
    <p>En la serie breaking bad hay un momento en el que se ilustra esto en la que W. White trata de comunicarse con su socio, que ha perdido a su compañera trágicamente, evidenciando de alguna manera la incapacidad de expresar de manera eficaz: “Estoy convencido de que existe una combinación de palabras; deben existir ciertas palabras que en un orden específico puedan explicar todo esto, pero no soy capaz de encontrarlas”. <br>En el libro de Nonaka y Takeuchi, podemos encontrar un ejemplo inmejorable de esa dificultad aplicada a la transferencia del conocimiento. La empresa Panasonic trataba de construir una máquina panificadora que produjese panes de calidad a precios asequibles. Para eso, contaban con grandes ingenieros y presupuesto. El problema era, que pan hacer. Y fueron a buscar al mejor panadero de Japón, al que preguntaron lógicamente, cuál era el secreto para hacer ese pan tan famoso en todo el país. El panadero se encogió de hombros y lamentó profundamente no poder dar una respuesta ya que él la desconoce. <br>En realidad, el panadero  no desconocía la respuesta, todo lo contrario: era el único propietario de la misma. El problema radica en su capacidad de transmitirlo.</p>
    <p>Independientemente del aspecto cognitivo en el cuál el panadero sería reacio a compartir su conocimiento, el aspecto comunicativo informal jugaba un papel crucial. No importaba lo importante o grande que fuese la empresa: necesitaban del conocimiento de un solo panadero. <br>En una empresa, una familia o en definitiva, en un grupo humano cuando ese conocimiento comienza a generar comunidad a su alrededor es cuando tiene un verdadero impacto social visible para el gran grupo. Pero solo después de que un pequeño grupo de innovación, haya visto el impacto antes que el gran grupo (curva de Rogers).</p>
    <h4>Elige bien la cafetería</h4>
    <p>Hablar de café en un equipo suena a descanso. A echar un cigarro rápido y otra vez al lío. A conversaciones sobre partidos de fútbol o famosos. Pero también a usos prácticos, herramientas, métodos, contenidos…<br>Igual que antes hablábamos de la conversación intergeneracional, también podemos recordar un momento “café” en el que alguien referente en el sector en el que nos movíamos, nos dió una información que nos hizo conectar de manera inmediata y resolvió de un plumazo el enigma que nos atormentaba hasta entonces. Es ese <b>“sorprendizaje”</b> del que habla <a href="https://twitter.com/yoramonbarrera" target="_blank">Ramón Barrera</a>, que rompe una barrera mental y despliega el mapa que mirábamos en todas direcciones, proporcionando nuevos ámbitos de estudio desde la pregunta inicial.</p>
HTML;
$contenido3 = <<<HTML
    <p>Ese café, real o virtual, es en esencia el know-how no escrito de la organización. la representación informal de la inteligencia colectiva del equipo. Puede llegar a ser incluso avalista de la propuesta de valor y la que garantice que el equipo sea propietario del conocimiento que necesita para realizarla. <br>Es vital, por lo tanto, elegir con cautela a nuestro interlocutor en ese proceso de socialización. Sin duda, este agente puede estar en el exterior pero estamos hablando de la organización y de que quien tiene realmente el conocimiento sobre la propuesta de valor, es el propio equipo. <br>Panasonic tenía claro su propuesta de valor y no la quería del panadero sino que buscaba específicamente la solución a la brecha de conocimiento que existía en uno de sus procesos. <br>El proceso de hacer el pan estaba muy documentado, pero ninguno explicaba lo que el panadero hacía. Fueron necesarias muchas horas de seguimiento y observación para establecer finalmente que activadores necesitaban los ingenieros incorporar para realizar un pan similar. </p>
    <p>Panasonic escogió bien su cafetería. Para poder desarrollar un know-how de calidad, primero necesito un how-know de alto impacto. Su pregunta, ¿cómo podríamos hacer el mejor pan de una manera automatizada? les llevó a cuestionar cada paso del proceso y encontrar a los profesionales y expertos de referencia en cada paso. La transmisión de ese conocimiento tácito, desde el punto de vista de la ingeniería y el diseño, permitió apuntalar los principios de un nuevo producto o lo que es lo mismo, la semilla de la innovación.<br>Por cierto, si os lo preguntáis, el secreto del pan era la masa. Más concretamente los pies del panadero que eran, las herramientas fundamentales para el amasado y con los que controlaba con una sensibilidad especial la textura y la humedad. Podría haberse dado lugar a que el panadero asumiese que era el amasado con los pies lo fundamental del proceso y transmitirlo así. Y Panasonic habría puesto pies a su maquinaria. Fué necesaria la mirada desde otro punto de vista para lograr descifrar el código de trabajo identificando los parámetros básicos de operativa del panadero y emular el proceso con maquinaria y sensores específicos.<br>En definitiva, hay mucho más conocimiento dentro de nuestra organización del que figura en currículos y mapas de competencias (por útiles que estos sean) y pasa desapercibido por, entre otras cosas, no compartir un buen café. </p>
HTML;
include 'plantillaPost.php';
?>