<?php
$titulo = "Mi vida como CLOer";
$autor="Rubén Jerónimo";
$categoria="Aprendizaje";
$fecha="21 de octubre, 2020";
$subtitulo = "Objetivos y resultados clave en el aprendizaje";
$imagen1 = "https://www.shutterstock.com/image-vector/pattern-welcome-back-school-background-600w-725655688.jpg";
$imagen2 = "";
$contenido1 = <<<HTML
    <p id="descripcionPost">¡Hola! Soy <a>Rubén Jerónimo</a><br> (ingeniero de carrera, emprendedor y team coach en lo profesional y aprendiz en la vida, además de papá) y ya tengo 43 castañas, lo que significa que en román paladín, tengo más palos que una estera. <br>Jamás me había sentido en una experiencia de aprendizaje como la que estamos viviendo en CLO, el título propio de la universidad de Mondragón de Chief Learning Officer, una figura de reciente aparición en el mundo de las grandes organizaciones y que cada vez tendrá más repercusión en empresas y organismos. <br>Más allá de la potencia del rol, que la tiene, me gustaría hablar de la propia experiencia de formación como CLOer. Un recorrido por cinco módulos que van desde el diseño de experiencias de aprendizaje hasta el lifelong learning pasando por facilitación de equipos, complexity navigation y people analytics. <br>El primer contacto que tuve con esta titulación, que este año está formando a la segunda generación, fue el año anterior cuando tuve la oportunidad de ser el facilitador del módulo de Facilitación de equipos. Entonces, ya pude ver algo distinto en la forma en la que las personas usuarias estaban adquiriendo sus conocimientos. Era un espacio tan propicio para el aprendizaje que este año quería tener la experiencia completa por mí mismo desde el punto de vista de Rubén como usuario. Y no puedo tener mejor impresión.</p> 
HTML;
$contenido2 = <<<HTML
    <p>Comenzar un nuevo ciclo formativo conlleva mucha ilusión y energías que, en no pocas ocasiones, acaban siendo malgastadas. <br>El grupo al que perteneces en tu formación es fundamental para el proceso. Y en el caso de la 2ª generación de CLO, tengo que reconocer el gran trabajo que se ha realizado para seleccionar los perfiles. Todo un abanico personas y profesionales que cuentan con habilidades complementarias, trayectorias y perspectivas diferentes que aportan en cada sesión, una multitud de ideas y acciones concretas.<br>Mi equipo de CLO ha demostrado ser todo un ejemplo de compañerismo, empatía y sobre todo, de trabajo incansable para obtener trabajos promotores inspiradores y de calidad.<br>¿No os pasa que sois más eficientes o tenéis mejores ideas en según qué ambiente? Claro Rubén, qué cosas tienes… pues este team es tan propicio a que eso suceda que os invito a que participéis de la siguiente generación que estoy seguro, tendrá un proceso de selección que generará todo un equipazo. <br>Ni que decir tiene que si yo tengo un dream team es porque hay otro conjunto de profesionales detrás que se encarga de que todo funcione como debe funcionar.  Y me refiero al tándem Huhezi-Teamlabs que son en definitiva, las agentes que han generado todo esto. <br>Pero si quiero hilar fino (y vaya que si quiero) tengo que citar a las verdaderas almas de esto: Beatriz García y Ana Rodera.  Contar con estas primeras espadas de la educación hace fácil lo difícil. No hay situación en la que podamos ver un equipo tan perfectamente engrasado y con un atractivo muy singular a la hora de plantear experiencias de facilitación del aprendizaje.<br>No es que lo hagan bien, que es que sí, es que lo hacen distinto. Echan muchas ganas y esfuerzos en conseguir que CLO fluya y permita ayudarnos a navegar la incertidumbre proponiéndonos un acompañamiento de 10 o más. Desde aquí solo puedo decir: muchas gracias, ¡no flojeéis que os necesitamos!<br></p>
                                    <h2>Píldoras de conocimiento</h2>
                                    <p>Quizá es pronto para generalizar, pero si la tónica general se mantiene y el resto de módulos tienen la misma calidad que los ya vistos, puede ser en mi opinión, uno de los repositorios con más calidad y curación de contenidos que haya visto jamás (en las más de cuatro décadas de existencia que tengo).<br>Y no solo por el conocimiento implícito en los textos sino por el cariño en la edición, lo sugerente de la maquetación y el impacto que los conceptos provocan en el recorrido por los contenidos. Todo lo anterior se une para brindar un viaje más que apetecible del que nunca te cansas de observar el paisaje, siempre cambiante y provocador de sinapsis. <br>Puede que hayas oído o leído algo (o todo) sobre los temas de los módulos. De lo que estoy seguro es de que nunca lo verás y vivirás así.<br>Ni que decir tiene la importancia de que el contenido esté incluido en un contenedor atractivo para poder poner foco en lo realmente importante que son los conceptos, las ideas y la transferencia de conocimientos en la realidad de cada persona. Bien, pues CLO ha conseguido uno de los ambientes de aprendizaje colaborativo más completos y arrulladoras con los que me he topado.<br></p>
                                    <h2>Aplicación y práctica</h2>
                                    <p>Desde el primer día, CLO se centra en la parte más humana de los procesos de aprendizaje y eso, no hay libro que nos lo descubra.<br>Los insights en este campo los adquirimos cuando nos ponemos a trabajar. Y eso es precisamente lo que se hace desde el día uno (casi casi desde que te matriculas), ya que el punto de partida es diseñar un proyecto. Empieza con uno que tengas o inícialo aquí, todo vale para empezar a tirar del hilo e ir hilvanando una propuesta de acción de aprendizaje de impacto.<br>Cada cosa que ves en contenido tiene su reflejo en la aplicación directamente y con la capacidad de medir su impacto. Solo puedo decir, ¡no he podido parar ni un día!<br></p>
                                    <h2>Para ir cerrando</h2>
                                    <p>Ante una perspectiva tan amplia como la definición de un nuevo rol/profesión/lo que sea, es fácil que vende-motos y gente con pocos escrúpulos actúen como entes expertas y caigamos en su red ante la falta de información. La sensación de recibir más de lo que esperabas es justo lo contrario de esa situación y es precisamente lo que encuentras en CLO.<br>Este diploma ayuda a construcción el diseño de un futuro profesional con unas estrategias de facilitación y herramientas que pueden llegar a afectar positivamente a la sociedad. Se trata de un espacio generador de nuevos conocimientos e impulsor de nuevas acciones y proyectos, ¡ahí es nada!<br>Eso sí, no es para todo el mundo. Si no te gustan los retos, te cuesta aceptar el cambio o simplemente, vas a esgrimir una excusa, no vengas a CLO.  Si por el contrario crees que tus mejores ideas están aún por llegar, acércate un poco más. Sí, sí, un poco más. Otro poco más… ya casi, casi eres CLOer.<br></p>
HTML;
$contenido3 = <<<HTML
    <p></p>
HTML;
include 'plantillaPost.php';
?>