<?php
$titulo = "Estrategia en el aprendizaje organizacional";
$autor="Rubén Jerónimo";
$categoria="Estrategia";
$fecha="11 de agosto, 2024";
$subtitulo = "Cómo sabemos lo que sabemos.";
$imagen1 = "https://img.freepik.com/foto-gratis/escritura-gesto-direccion-guapo-ahorro_1134-1051.jpg?w=1380&t=st=1684918500~exp=1684919100~hmac=41f2d435844b5ddc55a493720663baf03e3f6a7289aabfff5f82166eb0deaeb0";
$imagen2 = "https://img.freepik.com/foto-gratis/escritura-gesto-direccion-guapo-ahorro_1134-1051.jpg?w=1380&t=st=1684918500~exp=1684919100~hmac=41f2d435844b5ddc55a493720663baf03e3f6a7289aabfff5f82166eb0deaeb0";
$contenido1 = <<<HTML
    <p id="descripcionPost">La gestión del conocimiento es una de las claves para el éxito de cualquier organización, ya que permite la creación, almacenamiento, transferencia y aplicación del conocimiento dentro de la empresa. Sin embargo, para gestionar el conocimiento de manera efectiva, antes necesitamos conocer lo que la organización sabe y cómo se comparte ese conocimiento.<br>Es aquí donde la cartografía del conocimiento entra en juego.<br>El mapeo del conocimiento es el proceso de representar visualmente información y datos complejos relativos al conocimiento que proporciona,genera, crea… valor y propósito en la organización. Nos ayuda a comprender mejor las relaciones entre los elementos, optimizar nuestra comprensión sistémica de las capacidades, agilizando conexiones e identificando los próximos pasos de aprendizaje.<br>La cartografía del conocimiento es un proceso que permite visualizar y comprender cuál es el conocimiento real y verdaderamente importante dentro de una organización y cómo fluye dentro de la misma. Es una herramienta esencial para identificar personas expertas en diferentes áreas, compartir conocimientos entre equipos y mejorar el aprendizaje del equipo.<br>Sabemos de sobra la importancia del conocimiento dentro de la organización y de hecho, la mayor parte de las empresas contratan por las capacidades y habilidades personales conscientes de que es la persona quien es propietaria del conocimiento. Sin embargo, pocas parecen tener la misma consciencia cuando se trata del equipo, del proyecto o de la organización.</p>
HTML;
$contenido2 = <<<HTML
    <p>Aunque sabemos que esta tendencia está cambiando, aún queda mucho camino por recorrer y, el auge de la tecnología impulsada por IA, parece que puede ayduar a acelerar esta tendencia. <br>estas organizaciones están aprovechando las oportunidades para administrar mejor sus conocimientos y recursos. A medida que esta tendencia siga creciendo, las empresas y organizaciones se volverán más eficientes, productivas y rentables.<br>Pero la gestión del conocimiento parte desde algo más humano y podemos comenzar hoy mismo.<br>Parece lógico comenzar definiendo un marco de observación ya que este nos aproximará de manera diferente. Podemos establecer ese marco desde las necesidades o decisiones estratégicas, o quizá desde la mejora de procesos concretos. Identificando el marco adecuado para la situación, permite diseñar el espacio capacitativo necesario y por lo tanto, el observable dentro de la organización.<br>Si el proceso se basa en las personas, contextualizar puede acercarnos a nuestro objetivo. Explorar los planes de carrera de los miembros del equipo y determinar así una matriz de competencias nos permitirá tener un listado detallado de cuáles son las competencias necesarias, cuánto tiempo serán necesarias o quien las tiene. Las conexiones entre las soft y hard skills nos proporcionan una información muy valiosa de que tipo de organización desde el punto de vista de la cultura de aprendizaje.<br>Al determinar el contexto podemos iniciar un proceso de conciliación, en el que establecer la adecuación puesto-persona exceda las competencias y que van en búsqueda de valores y habilidades que facilitan el trabajo en equipo, el liderazgo y autoliderazgo, la búsqueda del equipo de alto rendimiento y la construcción de espacios generativos de nuevo conocimiento.<br>Se crea aquí, una necesidad de planificación de la gestión del conocimiento con estos nuevos descubrimientos y este, no puede estar desligado de la propia cultura de organización, más allá de la propia cultura de aprendizaje organizativo, las formas y modos dentro de la organización determinan no solo los cómos, si no los qués y los porqués, dando resultados muy diversos desde la ya muy conocida formación a las comunidades de práctica, comunidades de aprendizaje,…<br>Podemos dar un último paso al evaluar los cambios y resultados producidos con este mapeado ya que esto nos llevaría a tener conocimiento del propio conocimiento y como afecta en la organización. Los indicadores intangibles aún siendo mucho más complejos que los tangibles, nos dan una información reveladora para el crecimiento. Identificar los tangibles que afectan a los intangibles, su impacto y magnitud, relevancia y recursos pueden darnos pautas para “medir” lo que es difícil.</p>
HTML;
$contenido3 = <<<HTML
    <p></p>
HTML;
include 'plantillaPost.php';
?>