<?php
$titulo = "Midiendo huellas en el agua";
$autor="Rubén Jerónimo";
$categoria="Indicadores";
$fecha="6 de junio, 2023";
$subtitulo = "Transformando las herramientas de evaluación";
$imagen1 = "https://equiposqueaprenden.es/knowriish/blog/imagenes//midiendohuellas1.jpg";
$imagen2 = "https://equiposqueaprenden.es/knowriish/blog/imagenes/midiendohuellas2.jpg";
$contenido1 = <<<HTML
    <h4>Evaluar lo invisible</h4>
    <p id="descripcionPost">En nuestra necesidad humana de medir y comparar el progreso, a menudo nos enfrentamos a conceptos abstractos y la búsqueda de evidencias con las cuales identificarnos. <br>Cuando hablamos sobre aprendizaje en organizaciones nos encontramos en estos casos.<br>Es en este contexto que surge la generación de usos distintos a los concebidos inicialmente, desafiando nuestras formas tradicionales de medición y evaluación.</p><br>
HTML;
$contenido2 = <<<HTML
    <p>Como cartógrafo, mi labor consistía en crear mapas precisos. Anteriormente, utilizaba coordenadas cartesianas sin ambigüedades, representando características físicas y límites con exactitud. Esta precisión nos ha permitido lograr avances tecnológicos, como aterrizajes automatizados de aviones, gestión eficiente de flotas de vehículos y la capacidad de ubicarnos con precisión a través de estaciones de tierra y dispositivos móviles.<br>Sin embargo, esta precisión está limitada a un espacio documentado que permanece inalterable y dentro de fronteras definidas. Esta situación contrasta dramáticamente con la realidad que vivimos, caracterizada por su volatilidad, incertidumbre, complejidad y ambigüedad (VUCA, por sus siglas en inglés).<br>Se trata de todos esos intangibles de límites difusos, no siempre contemplados desde el mismo punto de vista por los miembros del equipo.<br>No disponemos de un laboratorio donde podamos analizar y medir la realidad de manera controlada, ya que los eventos no se repiten en el tiempo con las mismas características.</p>
    <p>Pareciera que nos despedimos del espíritu científico, pero tal vez haya una alternativa.<br></p>
    <h4>Límites difusos</h4>
    <p>Se dice que los seres humanos nos sentimos reconfortados con la idea de un dios, ya que nos resulta difícil asumir el concepto de infinito. Similarmente, cuando nos enfrentamos a los famosos KPIs (Indicadores Clave de Desempeño), a menudo nos cuesta dar sentido a las acciones que realizamos y su impacto directo en los resultados. Nos encontramos con gestores de todo tipo que presentan indicadores que poco tienen que ver con el núcleo de lo que se está estudiando. Estos indicadores suelen apuntar hacia situaciones pasadas que el gestor reconoce y con las cuales siente cierta comodidad, ya que parece que alguien tiene el control de la situación.</p>
HTML;
$contenido3 = <<<HTML
    <p>No obstante, en entornos cambiantes, debemos considerar que las cuestiones reconocibles en otros segmentos del pasado solo nos brindan sugerencias para el futuro, no una hoja de ruta exacta. Tanto el contexto como los agentes involucrados son diferentes, lo que implica que los procesos y los resultados también pueden variar.<br>Aquí es donde tomo la sugerencia de Stacey Barr y su enfoque basado en evidencias. Aunque sigue siendo difícil asignar indicadores a conceptos intangibles, al menos evitamos el uso de palabras vacías que carecen de impacto en nuestros objetivos, pero que se han vuelto populares. Las evidencias, por otro lado, se revelan como huellas en el camino, una descripción precisa de los hechos que nos permiten definir KPIs intangibles de calidad. En lugar de enfocarnos en qué queremos "medir", nos centramos en el impacto que deseamos lograr, lo cual tiene más sentido y es más fácil de identificar.</p>
    <h4>Dibujar en el humo</h4>
    <p>No podemos permitirnos evaluar únicamente los impactos positivos o los conocidos. Es mucho más interesante plantearnos preguntas sobre los impactos desconocidos y tratar de definir posibles escenarios para esos futuros impactos, estableciendo las actividades y procesos necesarios para abordarlos.<br>Podemos ir más allá y considerar esas huellas como puntos intermedios en un camino de aprendizaje que nos llevará a un mayor conocimiento de nuestra propuesta de valor. En <a href="OKR4L.html">OKR4L (Objetivos y Resultados Clave para el aprendizaje)</a>, los llamamos resultados clave, y han sido diseñados específicamente para evaluar el estado de éxito parcial en un proceso completo, permitiéndonos contrastar la condición teórica con la real y ajustar nuestra estrategia en consecuencia.</p>
    <img src="imagenes/midiendohuellas3.jpg" style="width: 400px; display: block; margin: 0 auto;"><br>
    <p>Finalmente, creo que es importante destacar una diferencia en el lenguaje que solemos utilizar. Como cartógrafo, se me enseñó a "medir", pero la medición implica un resultado frío y analítico, carente de profundidad. Sin embargo, <b>cuando cambiamos el verbo por "observar", todo cambia.</b> El resultado deja de ser un mero indicador de desempeño y se convierte en una línea de vida para el equipo.<br>Si llegamos a la conclusión de que no necesitamos tener el control absoluto de los acontecimientos, sino la información más precisa posible sobre ellos, el equipo deja de sentirse vigilado y comienza a sentirse empoderado. Aprender a observar en lugar de medir nos permite trascender la rigidez de los resultados fríos y analíticos. Al adoptar esta perspectiva, el equipo se libera de la presión constante y se enfoca en obtener la información más precisa de los acontecimientos. De esta manera, la observación se convierte en una herramienta vital que impulsa el crecimiento y el éxito del equipo.<br>Necesitamos un nuevo marco en la relación con los resultados y su evaluación, observando el entorno y el impacto, en lugar de medir sus huellas en el agua.</p>
HTML;
include 'plantillaPost.php';
?>