<?php
$titulo = "OKR4L";
$autor="Rubén Jerónimo";
$categoria="Planificación";
$fecha="21 de octubre, 2020";
$subtitulo = "Objetivos y resultados clave en el aprendizaje";
$imagen1 = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.simtutor.com%2Fmedia%2Fc5ulg4e1%2Fwriting-learning-objectives.jpeg&f=1&nofb=1&ipt=e8517f57bcde6c51e3be353044a8a683ea228a9a956967451c1b7b034915d006&ipo=images";
$imagen2 = "https://equiposqueaprenden.es/knowriish/blog/imagenes/OKR4L_Stakeholders.jpg";
$contenido1 = <<<HTML
    <p id="descripcionPost">Encontrar las vías para conseguir nuestras metas es casi siempre tarea difícil: falta de tiempo para organizar, hiperinformación que despista en el camino, urgencias varias, etc. pueden ser causas del fracaso de nuestras experiencias en el aprendizaje.<br>Sin embargo, tenemos procesos y recursos que pueden potenciar nuestro conocimiento. Para mí existen dos claves para que la curva de aprendizaje crezca exponencialmente: el <b>equipo</b> y el <b>propósito</b>.<br>Lógicamente son dos términos que pueden convivir con cierta hostilidad y de hecho, así ocurre en muchas ocasiones, ya que los <b>propósitos</b> individuales y los de equipo rara vez se exponen o se dedica tiempo para hacerlos coincidir. <br>Como bien dice <a href="https://twitter.com/rahego" target="_blank">Raúl Hernandez</a> en su libro Skillopment, es muy difícil engañar al cerebro para almacenar una información si no existe un propósito detrás. Y esto será más fácilmente asumible solamente si lo cuestionamos. Por tanto, el proceso de aprendizaje humano, pasa en cualquier caso por la <b>aplicación</b> o se quedará en simple conocimiento (no estoy despreciando, solo filtrando). Por eso, sí o sí tenemos que pasar a la acción para evaluar, observar y determinar unos siguientes pasos. <br>Las personas somos  “bichos” que aceptan muy bien los procesos cuando los entienden y, mucho mejor, cuando los diseñan y son partícipes de su creación. Sin embargo, también nos podemos bloquear ante circunstancias como el exceso de inputs informativos o sobre todo, momentos de crisis.<br>Si volvemos a poner en el centro al equipo y al propósito, surge una herramienta que aunque provenga del mundo de la empresa, puede tener y de hecho lo tiene, mucho sentido en los procesos de aprendizaje.</p><br>
HTML;
$contenido2 = <<<HTML
    <p><b>La distribución de objetivos desde el propósito más profundo</b> hace que seamos mucho más conscientes de estos en todo momento y planifiquemos desde el pragmatismo. Así, quien posee una competencia tiene capacidad para una acción concreta basada en su conocimiento y experiencia y es lo que busca en definitiva un objetivo de OKR4L (<b>OKR for learning</b>).<br>Aterrizo un poco más esta parte. No puedo pasar por alto una de las cosas que más me llamaron la atención cuando <a href="https://twitter.com/loogic" target="_blank"> Javier Martín</a> de Sngular me presentó el sistema OKR.  Y estos son los superpoderes: concentración, coordinación, seguimiento y exigencia parecen ser idóneos para un entorno de aprendizaje. <br>Cada uno de los superpoderes anteriores se pueden también cultivar dentro de un entorno de aprendizaje y de hecho, debemos hacerlo, aplicando un conjunto de herramientas y sesiones de mentoría que ayudan a los usuarios a perfilar y desarrollarlas.</p>
    <p><b>La distribución de objetivos desde el propósito más profundo</b> hace que seamos mucho más conscientes de estos en todo momento y planifiquemos desde el pragmatismo. Así, quien posee una competencia tiene capacidad para una acción concreta basada en su conocimiento y experiencia y es lo que busca en definitiva un objetivo de OKR4L (<b>Objetives and key results for learning</b>).<br>Aterrizo un poco más esta parte. No puedo pasar por alto una de las cosas que más me llamaron la atención cuando <a href="https://twitter.com/loogic" target="_blank"> Javier Martín</a> de Sngular me presentó el sistema OKR.  Y estos son los superpoderes: concentración, coordinación, seguimiento y exigencia parecen ser idóneos para un entorno de aprendizaje. <br>Cada uno de los superpoderes anteriores se pueden también cultivar dentro de un entorno de aprendizaje y de hecho, debemos hacerlo, aplicando un conjunto de herramientas y sesiones de mentoría que ayudan a los usuarios a perfilar y desarrollarlas.</p>
    <p>El propósito del aprendizaje teórico sería como un dibujo de toda la vida de aprendizaje o lifelong learner, pero desde el punto de vista más ambicioso y aspiracional, mientras que los objetivos de aprendizaje se convierten en pasos tácticos y operativos que concluyen realidades y lo evidencian. <br>Los OKR4L permiten identificar desde un reto o necesidad, los propósitos profundos de aprendizaje personal y de equipo dotando de herramientas para la gestión de la información, el flujo del conocimiento, la autoevaluación y sobre todo, la aplicación y la escalabilidad del aprendizaje. <br>A su vez, estos OKR4L actúan como activadores o como una enzima que cataliza los procesos de aprendizaje de un equipo entorno a unos retos y objetivos concretos, pero sobre todo reales. A su vez, impactan en las acciones derivadas de la aplicación de un conocimiento concreto y dota de herramientas de observación, medición y evaluación del aprendizaje de una manera inclusiva.</p>
HTML;
$contenido3 = <<<HTML
    <p>Y no puede ser de otra manera. Una facilitación ideal de OKR4L no es un entorno amparado por contenidos y metodologías. Es una invitación al reto constante y eso incluye el diseño inicial de habilidades y competencias que bajo un sistema de rúbricas identifiquen sin ambigüedad, el nivel que se posees en determinadas habilidades y competencias. <br>A la hora de planificar, las etapas de aprendizaje, es necesario determinar plazos de entrega para las evidencias que serían en este caso, los entregables o mejor dicho los resultados de aprendizaje.<br>Hay que, por un lado, empoderar al equipo para que esa medida determine la ambición y la aspiración en el aprendizaje y recordar continuamente que un aprendizaje más dirigido hacia su propósito, conseguirá mejores resultados. Y, por otro lado, potenciar la capacidad de adaptabilidad al entorno y sobre todo, a sus cambios (aunque este hecho vendrá determinado por los aprendizajes).<br></p>
    <img src="imagenes/OKR4L.jpg" style="width: 600px; display: block; margin: 0 auto;">
    <p>Hay que tener en cuenta que la capacidad de concentración para llegar a resultados dentro de una compañía puede ser muy distinta de los objetivos de aprendizaje dentro de un equipo. Puede hasta que estos dos equipos confluyen en uno mismo y podamos determinar que los objetivos de resultados de la compañía pueden ser la medida que determina los resultados de aprendizaje del equipo, ejemplo de lo importante que es la aplicación. <br>En definitiva, OKR4L pretende dotar de un marco a equipos para encontrar sus propias herramientas de aprendizaje impactando en la cultura del propio equipo: aprendiendo cómo aprenden.  Se trata de una herramienta apta para el upskilling y reskilling dentro de un entorno de aprendizaje continuo y motivacional. <br>No os digo más, tenéis que probarlo. </p>
HTML;
include 'plantillaPost.php';
?>